config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources :books
  resources :users
  namespace :admin do
    root to: "home#index"
    resources :books
    resources :users
    resources :borrows
  end
end

app/models/book.rb
class Book < ActiveRecord::Base

  has_many :borrows

  validates :title, presence: true

  default_scope {order :title}

  state_machine initial: :available do

    state :unavailable
    state :available
    state :on_hold
    state :borrowed
    state :lost

    event :place_hold do
      transition available: :on_hold
    end

    event :borrow do
      transition on_hold: :borrowed
    end

    event :return do
      transition borrowed: :available
    end

    event :enable do
      transition all => :available
    end

    event :disable do
      transition all => :unavailable
    end

  end

end

app/models/borrow.rb
class Borrow < ActiveRecord::Base

  belongs_to :book
  belongs_to :user

  after_create :change_book_state

  state_machine initial: :active do

    state :active
    state :returned
    state :overdue
    state :lost

  end

  private

  def change_book_state
    self.book.borrow
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :borrows

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable,
    :trackable, :validatable

  def is_admin?
    self.id == 1
  end

  def current_borrows
  end

  def past_borrows
  end

end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController

  before_action :authenticate_user!
  before_action :require_admin

  layout "admin"

  private

  def require_admin
    redirect_to root_path unless current_user.is_admin?
  end

end

app/controllers/admin/books_controller.rb
class Admin::BooksController < Admin::BaseController

  before_action :load_book, only: [:edit, :update, :destroy]

  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new book_params
    if @book.save
      redirect_to @book
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @book.update book_params
      redirect_to @book
    else
      render :edit
    end
  end

  def destroy
    @book.destroy
    redirect_to admin_books_path
  end

  private

  def book_params
    params[:book].permit!
  end

  def load_book
    @book = Book.find params[:id]
  end

end

app/controllers/admin/borrows_controller.rb
class Admin::BorrowsController < Admin::BaseController

  def index
    @borrows = Borrow.all
  end

end

app/controllers/admin/home_controller.rb
class Admin::HomeController < Admin::BaseController

  def index
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController

  def index
    @users = User.all
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
  end

  def show
    @book = Book.find params[:id]
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
  end

  def edit
  end

  def update
    if current_user.update user_params
      redirect_to current_user
    else
      render :edit
    end
  end

  private

  def user_params
    params[:user].permit :name, :address, :phone
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/books/_form.slim
= form_for [:admin, book] do |f|
  .block
    fieldset
      legend Basic Info

      p
        = f.label :title
          | Title
          span.req<> *
          span.forms-desc<> Always nice to feel important.
        br
        = f.text_field :title, placeholder: "Norwegian Wood", class: "input-gray width-50"
      p
        = f.label :author
        br
        = f.text_field :author, placeholder: "Haruki Murakami", class: "input-gray width-50"

  .block
    fieldset
      legend Description
      = f.text_area :description, id: "description"

  .block
    fieldset
      legend Publication Info
      
      p
        = f.label :publisher
        br
        = f.text_field :publisher, class: "input-gray width-50"

      p
        = f.label :isbn_10, "ISBN-10"
        br
        = f.text_field :isbn_10, class: "input-gray width-50"

      p
        = f.label :isbn_13, "ISBN-13"
        br
        = f.text_field :isbn_13, class: "input-gray width-50"

  .block
    = f.button :submit, class: "btn btn-green width-40"

app/views/admin/books/edit.slim
h1 Edit book

= render "form", book: @book

javascript:
  $(function(){
    $('#description').redactor(
    {
      placeholder: 'Add book description here...'
    });
  });

app/views/admin/books/index.slim
.block
  = link_to "Add a book", new_admin_book_path, class: " btn btn-green"

- @books.each do |book|
  .block
    | #{book.id}
    = link_to book.title, book_path(book)

app/views/admin/books/new.slim
h1 Add new book

= render "form", book: @book

javascript:
  $(function(){
    $('#description').redactor(
    {
      placeholder: 'Add book description here...'
    });
  });

app/views/admin/borrows/index.slim
- @borrows.each do |borrow|
  .block
    = borrow.id
    |
    = borrow.book.title
    |
    = borrow.user.name

app/views/admin/home/index.slim
.block
  h1 At a glance
  div
    | Number of books: #{Book.count}
    br
    | Number of users: #{User.count}

app/views/admin/users/index.slim
- @users.each do |user|
  .block
    | #{user.id}
    | #{user.name}

app/views/books/index.slim
.block
  input.input-gray.width-50 type="text" placeholder="book title or author"
  button.btn.btn-green Search
  br
  br
  | ALL 
  | #
  span<>
  - ("A".."Z").each do |char|
    = char
    span<>

- @books.each do |book|
  .block
    = link_to book.title, book
    em<> by
    | #{book.author}
    br
    = book.state

app/views/books/show.slim
.block
  h1 = @book.title
  table
    tr
      td Author
      td = @book.author
    tr
      td Publisher
      td = @book.publisher
    tr
      td Year
      td = @book.year
    tr
      td ISBN-10
      td = @book.isbn_10
    tr
      td ISBN-13
      td = @book.isbn_13
.block
  - if @book.available?
    = link_to "Place hold", holds_path(book_id: @book.id), method: :post, class: "btn btn-green"
  - elsif @book.unavailable?
    | This book is currently unavailable. You cannot borrow it.
  - elsif @book.on_hold?
    | This book is currently on hold. You cannot borrow it.
  - elsif @book.borrowed?
    | This book is currently borrowed by someone. You cannot borrow it.
  - else 
    | This book is lost.

app/views/home/index.slim
.block
  button.btn.btn-green About
  span<>
  button.btn.btn-green Contact
  span<>
  button.btn.btn-green Policy

.block
  h1 Home page

app/views/layouts/admin.slim
doctype html
html
  head
    title Littlelibrary
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  
  body
    #wrap
      #nav
        ul.admin
          li = link_to "OVERVIEW", admin_root_path
          li = link_to "BOOKS", admin_books_path
          li = link_to "USERS", admin_users_path
          li = link_to "BORROWS", admin_borrows_path
          li = link_to "SITE", root_path

      #main
        p.notice = notice
        p.alert = alert
        = yield

app/views/layouts/application.slim
doctype html
html
  head
    title Littlelibrary
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  
  body
    #wrap
      #nav
        ul.site
          li = link_to "HOME", root_path
          li = link_to "BOOKS", books_path     
          - if current_user
            li = link_to "MY ACCOUNT", current_user
            - if current_user.is_admin?
              li = link_to "ADMIN", admin_root_path
          - else
            li = link_to "SIGN IN", new_user_session_path
          

      #main
        p.notice = notice
        p.alert = alert
        = yield

app/views/users/edit.slim
.block
  h1 Edit profile

= form_for current_user do |f|
  .block
    fieldset
      legend Basic Info

      p
        = f.label :name
          | Your Name
          span.req<> *
        br
        = f.text_field :name, class: "input-gray width-50"
      p
        = f.label :address
        br
        = f.text_field :address, class: "input-gray width-50"

  .block
    = f.button :submit, class: "btn btn-green"

app/views/users/show.slim
.block
  = link_to "Edit Profile", edit_user_path(current_user), class: "btn btn-green"
  span<>
  = link_to "Sign out", destroy_user_session_path, class: "btn btn-green", method: :delete

.block
  h1 Profile

  div
    | Name: #{current_user.name}
    br
    | Address: #{current_user.address}
    br
    | Phone: #{current_user.phone}

.block
  h1 Current borrow

.block
  h1 Past borrow